### ISSUE TITLE
Composer?

### ISSUE THREAD

**Issue by kathiedart** [LukeMadhanga/PHPDocumentParser#1]
It would be great to install this from composer and track upstream. Would you consider it?

**Comment by LukeMadhanga** [comment]
I'd be up for that. Not used composer before, could you link me to get it set up

**Comment by dandart** [comment]
have a look at the docs at https://getcomposer.org/ and look for other projects for examples :D

**Comment by LukeMadhanga** [comment]
I've finally got to this (not had much time out of work). I've learned how composer works now from the link you provided. You can get it [here](https://packagist.org/packages/lukemadhanga/php-document-parser)

**Comment by kathiedart** [comment]
Looks like there's no autoload section, so projects using this won't be able to access the files by autoloading from just composer.

I'll look into making this work for our cases and will PR to you if you haven't already made it work.

Cheers
