### ISSUE TITLE
Namespace problems on import with laravel

### ISSUE THREAD

**Issue by YuriScarbaci** [LukeMadhanga/PHPDocumentParser#5]
Hello, I tried to import this library for a laravel project but I had lots of problem, composer won't load it correctly for some reason, in the end i had to manually include the class itself in the autoload file section of the composer.json file and modify part of the code to make the namespace works

you need to prepend a "\" to all the default php class instances,
(e.g. DOMDocument would have to become \DOMDocument , DOMXPath -> \DOMXPath , ZipArchive -> \ZipArchive )

thanks for the library, hope you can figure out why composer won't load it correctly in laravel and maybe do a provvider service for laravel with this library too?

**Comment by LukeMadhanga** [comment]
Thanks Yuri - the latest release `0.1.0` has those changes in, as well as a note to the user about php-zip. As stated in the release code, I never expected anyone to use this library as this repo was more a store for the projects that I play around with, thus all of the issues. I'm honoured that you use it.

I've also changed the autoload structure. I will close on confirmation that it works for you (I've tested and it works for me).
