### ISSUE TITLE
Check for empty $textnode in convertWordToHtml

### ISSUE THREAD

**Issue by hatcham** [LukeMadhanga/PHPDocumentParser#6]
With some docs I get the following error:

Uncaught TypeError: Argument 1 passed to LukeMadhanga\DocumentParser::renameTag() must be an instance of DOMElement, null given

Adding a check on the $textnode variable seems to fix:

Line 104:  if ($stylenodes && $stylenodes->length && $textnode) { ... }

**Comment by LukeMadhanga** [comment]
Implemented
